name: BUTool StatusDisplay CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout BUTool repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Checkout GenericDSAT plugin and submodules
      run: |
        git clone --branch develop \
          --recursive \
          --depth 1 \
          --shallow-submodules \
          https://gitlab.com/BU-EDF/GenericDSATDevice_plugin.git
    - name: Install dependencies
      run: |
        ls -lah .
        sudo apt install \
          libboost-regex-dev \
          build-essential \
          zlib1g-dev \
          libreadline-dev \
          libboost-dev \
          libboost-program-options-dev \
          libncurses5-dev
    
    - name: Build BUTool
      run: make
    - name: Build GenericDSAT plugin
      run: |
        cd GenericDSATDevice_plugin
        BUTOOL_PATH=$(realpath ../)
        source env.sh ${BUTOOL_PATH}
        make
    - name: Run StatusDisplay test
      run: ./run_BUTool_test.sh
    - name: Cleanup
      run: |
        make clean
        cd ${BUTOOL_PATH}
        make clean

        
